# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Isolated Gemini Explanation Service for Phase 5C (DEC-024).

This module implements the isolated explanation service that converts a
`GeminiAssessmentContext` into a structured, validated `FarmerAgriculturalResponse`
using Gemini 2.5 Flash, backed by an automated 3-stage validation pipeline and
a 100% deterministic pure-Python fallback generator.

Architectural Invariants:
1. Isolated Service: Not integrated into the production agent or orchestrator flow yet.
2. Controlled Prompt: Must exclusively use build_gemini_prompt(context).
3. Authoritative Assessment: Gemini is an explanation layer; it cannot mutate or
   override Phase 5B deterministic findings.
4. Multi-Layer Validation: Output must pass Pydantic schema validation, structural
   allowlist checks, epistemic invariant checks, and defense-in-depth banned content checks.
5. Deterministic-First Fallback: Any failure (network, parsing, validation) instantly
   routes to a deterministic template generator without raising unhandled errors to the caller.
6. Zero PII / Secret Leakage: API keys and credentials are never placed in prompts or responses.
"""

import json
import logging
import os
import re
from typing import Any, Literal, Protocol

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from app.assessment.gemini_prompt import build_gemini_prompt
from app.assessment.gemini_types import GeminiAssessmentContext
from app.config import config

logger = logging.getLogger(__name__)

# Allowed recommendation action literals (DEC-024 Allowlist)
AuthorizedActionType = Literal[
    "field_visual_inspection",
    "soil_moisture_manual_check",
    "ongoing_monitoring",
    "missing_information_gathering",
]

# Allowed urgency levels (Strictly limited to routine or advisory)
AuthorizedUrgency = Literal["routine", "advisory"]


class RecommendedNextStep(BaseModel):
    """Constrained, safe, evidence-linked field observation or monitoring step."""

    action_type: AuthorizedActionType = Field(
        description="Authorized low-risk field action category"
    )
    description: str = Field(
        description="Clear, low-risk practical step (e.g. 'Check soil moisture directly in the field')"
    )
    urgency: AuthorizedUrgency = Field(
        default="routine",
        description="Operational urgency level for field check (strictly limited to 'routine' or 'advisory')",
    )

    model_config = ConfigDict(frozen=True, extra="forbid")


class FarmerAgriculturalResponse(BaseModel):
    """Authoritative farmer-facing explanation payload generated by Gemini 2.5 Flash (DEC-024)."""

    language: str = Field(
        description="ISO language code of the response (e.g. 'en', 'hi')"
    )
    headline: str = Field(
        description="One concise summary sentence suitable for a mobile UI header"
    )
    summary: str = Field(
        description="2-3 sentence farmer-friendly overview of regional environmental conditions"
    )
    observations: list[str] = Field(
        description="Key observable facts cited directly from supporting evidence"
    )
    interpretation: str = Field(
        description="Farmer-friendly explanation of the deterministic Phase 5B assessment and patterns"
    )
    recommended_next_steps: list[RecommendedNextStep] = Field(
        default_factory=list,
        description="Zero or more safe, constrained field verification or monitoring steps",
    )
    limitations: list[str] = Field(
        description="Transparent caveats regarding data lag, resolution, or missing observations"
    )
    is_fallback: bool = Field(
        default=False,
        description="True if this response was generated by the deterministic fallback engine",
    )

    model_config = ConfigDict(frozen=True, extra="forbid")


class GeminiModelClient(Protocol):
    """Protocol for structured Gemini model invocation."""

    def generate_content(
        self,
        model: str,
        contents: str,
        config: Any | None = None,
    ) -> Any:
        """Generates content from the model given a prompt string and configuration."""
        ...


class DefaultGeminiClient:
    """Production Google GenAI SDK client wrapper."""

    def __init__(self) -> None:
        self._client: Any = None

    def _get_client(self) -> Any:
        if self._client is None:
            from google.genai import Client

            # Respect GOOGLE_GENAI_USE_VERTEXAI environment configuration
            use_vertex = os.getenv("GOOGLE_GENAI_USE_VERTEXAI", "False").lower() in ("true", "1")
            if use_vertex:
                self._client = Client(vertexai=True)
            else:
                self._client = Client()
        return self._client

    def generate_content(
        self,
        model: str,
        contents: str,
        config: Any | None = None,
    ) -> Any:
        client = self._get_client()
        return client.models.generate_content(
            model=model,
            contents=contents,
            config=config,
        )


# ==============================================================================
# Defense-in-Depth Banned Content Regexes
# ==============================================================================

BANNED_DOSAGE_PATTERNS: list[re.Pattern[str]] = [
    re.compile(
        r"\b\d+(?:\.\d+)?\s*(?:kg|grams?|gms?|litres?|liters?|ml|quintals?)\s*(?:/|per|\s+per\s+)\s*(?:acre|hectare|ha|bigha|guntha|katha)\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\b\d+(?:\.\d+)?\s*(?:kg|grams?|gms?|litres?|liters?|ml)\s+of\s+(?:urea|dap|fertilizer|npk|potash|mop)\b",
        re.IGNORECASE,
    ),
]

BANNED_CHEMICAL_PRESCRIPTIONS: list[re.Pattern[str]] = [
    re.compile(
        r"\b(?:apply|spray|use|inject|treat\s+with)\s+(?:urea|dap|glyphosate|mancozeb|chlorpyrifos|carbendazim|imidacloprid|monocrotophos|atrazine|paraquat|2,4-d)\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\b(?:urea|dap|glyphosate|mancozeb|chlorpyrifos|carbendazim|imidacloprid|monocrotophos|atrazine|paraquat|2,4-d)\s+dosage\b",
        re.IGNORECASE,
    ),
]

BANNED_IRRIGATION_DEPTHS: list[re.Pattern[str]] = [
    re.compile(
        r"\b(?:apply|irrigate\s+with|provide)\s+\d+(?:\.\d+)?\s*(?:cm|mm|inches|litres|liters|gallons)\s+(?:of\s+)?(?:water|irrigation)\b",
        re.IGNORECASE,
    ),
]

BANNED_ABSOLUTE_CLAIMS: list[re.Pattern[str]] = [
    re.compile(
        r"\b(?:fungal\s+blight|bacterial\s+rot|fusarium\s+wilt|rust\s+disease|leaf\s+spot)\s+(?:confirmed|diagnosed|detected)\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\b\d+%\s+(?:yield\s+loss|crop\s+loss|production\s+loss)\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bguaranteed\s+(?:100%|complete|total)\s+(?:crop\s+failure|loss)\b",
        re.IGNORECASE,
    ),
]


# ==============================================================================
# Multi-Layered Validation Logic
# ==============================================================================

def validate_response_payload(
    response: FarmerAgriculturalResponse,
    context: GeminiAssessmentContext,
) -> tuple[bool, str]:
    """Applies Stage 1-3 validations against a FarmerAgriculturalResponse.

    Returns:
        tuple[bool, str]: (is_valid, rejection_reason)
    """
    # 1. Structural / Basic Constraints
    if not response.headline.strip():
        return False, "Empty headline"
    if not response.summary.strip():
        return False, "Empty summary"
    if not response.interpretation.strip():
        return False, "Empty interpretation"

    # Normal Gemini response must not claim to be fallback
    if response.is_fallback:
        return False, "Non-fallback Gemini response had is_fallback=True"

    # 2. Epistemic Consistency Checks
    if (
        context.assessment_status == "insufficient_evidence"
        or context.overall_condition == "insufficient_evidence"
    ):
        # Must not claim thriving or favorable conditions when evidence is insufficient
        lower_summary = (response.headline + " " + response.summary).lower()
        if any(
            claim in lower_summary
            for claim in [
                "crop is thriving",
                "crop is completely healthy",
                "excellent crop health",
                "favorable growth condition",
                "फसल पूरी तरह स्वस्थ",
                "उत्कृष्ट स्थिति",
            ]
        ):
            return False, "Claimed favorable condition during insufficient evidence"

    # Must not invent numerical AI confidence or probabilities in interpretation
    if re.search(r"\b\d+%\s+confidence\b|\bconfidence\s+score\s*:\s*\d+", response.interpretation, re.IGNORECASE):
        return False, "Invented numerical confidence score in interpretation"

    # 3. Defense-in-Depth Banned Content Checks
    full_text = " ".join(
        [
            response.headline,
            response.summary,
            response.interpretation,
            *response.observations,
            *(step.description for step in response.recommended_next_steps),
            *response.limitations,
        ]
    )

    for pattern in BANNED_DOSAGE_PATTERNS:
        if pattern.search(full_text):
            return False, f"Banned quantitative dosage detected: {pattern.pattern}"

    for pattern in BANNED_CHEMICAL_PRESCRIPTIONS:
        if pattern.search(full_text):
            return False, f"Banned chemical prescription detected: {pattern.pattern}"

    for pattern in BANNED_IRRIGATION_DEPTHS:
        if pattern.search(full_text):
            return False, f"Banned irrigation depth prescription detected: {pattern.pattern}"

    for pattern in BANNED_ABSOLUTE_CLAIMS:
        if pattern.search(full_text):
            return False, f"Banned absolute claim detected: {pattern.pattern}"

    return True, "Valid"


# ==============================================================================
# Deterministic Fallback Generator
# ==============================================================================

FALLBACK_TEMPLATES = {
    "stable": {
        "en": {
            "headline": "Regional vegetative vigor and environmental conditions are aligned with seasonal normals.",
            "summary": "Satellite greenness, rainfall, and topsoil moisture match historical baselines for this time of year.",
            "interpretation": "Vegetation index and meteorological observations indicate normal seasonal growth without significant environmental anomalies.",
            "steps": [
                RecommendedNextStep(
                    action_type="ongoing_monitoring",
                    description="Maintain routine field observations and monitor weather forecasts over the coming week.",
                    urgency="routine",
                )
            ],
        },
        "hi": {
            "headline": "क्षेत्रीय फसल हरियाली और मौसमी स्थितियां सामान्य स्तर के अनुरूप हैं।",
            "summary": "उपग्रह से प्राप्त फसल हरियाली, वर्षा और मिट्टी की नमी इस मौसम के ऐतिहासिक सामान्य स्तर से मेल खाती है।",
            "interpretation": "वनस्पति सूचकांक और मौसम संबंधी आंकड़े किसी गंभीर असामान्यता के बिना सामान्य फसल विकास का संकेत देते हैं।",
            "steps": [
                RecommendedNextStep(
                    action_type="ongoing_monitoring",
                    description="खेत की नियमित निगरानी जारी रखें और आगामी सप्ताह के मौसम पूर्वानुमान पर नज़र रखें।",
                    urgency="routine",
                )
            ],
        },
    },
    "vegetation_stress": {
        "en": {
            "headline": "Satellite indicators show below-average vegetation vigor across the parcel.",
            "summary": "Vegetation greenness is lower than typical seasonal baselines, while meteorological indicators do not show acute weather deficits.",
            "interpretation": "Spectral vegetative departure indicates reduced canopy vigor that may warrant physical ground inspection to check localized conditions.",
            "steps": [
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="Inspect crop foliage across different parcel sections for visible wilting or uneven growth.",
                    urgency="advisory",
                )
            ],
        },
        "hi": {
            "headline": "उपग्रह संकेत खेत में मौसमी औसत से कम वनस्पति हरियाली दर्शाते हैं।",
            "summary": "फसल की हरियाली सामान्य मौसमी स्तर से कम है, जबकि मौसम के आंकड़ों में वर्षा की कोई गंभीर कमी नहीं दिखती।",
            "interpretation": "उपग्रह संकेत फसल के विकास में कमी दर्शाते हैं, जिसके लिए खेत में जाकर पौधों की स्थिति का निरीक्षण करना उचित रहेगा।",
            "steps": [
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="खेत के विभिन्न हिस्सों में जाकर पौधों की पत्तियों और विकास का प्रत्यक्ष निरीक्षण करें।",
                    urgency="advisory",
                )
            ],
        },
    },
    "moisture_stress_consistent": {
        "en": {
            "headline": "Satellite and weather indicators are consistent with environmental moisture stress.",
            "summary": "Rainfall deficit and reduced topsoil moisture align with below-average vegetative greenness.",
            "interpretation": "Observed dry conditions in both rainfall records and soil moisture corroborate lower vegetation vigor over the parcel.",
            "steps": [
                RecommendedNextStep(
                    action_type="soil_moisture_manual_check",
                    description="Check topsoil moisture at root depth with a hand-feel test before deciding whether irrigation is needed.",
                    urgency="advisory",
                ),
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="Inspect field for signs of moisture stress on leaf tips during peak sun hours.",
                    urgency="advisory",
                ),
            ],
        },
        "hi": {
            "headline": "उपग्रह और मौसम के आंकड़े नमी के तनाव की स्थिति के अनुरूप हैं।",
            "summary": "कम वर्षा और मिट्टी की ऊपरी परत में नमी की कमी के साथ फसल की हरियाली में गिरावट देखी गई है।",
            "interpretation": "कम वर्षा और कम मिट्टी की नमी के संयुक्त आंकड़े खेत में नमी की कमी (moisture stress) के अनुरूप हैं।",
            "steps": [
                RecommendedNextStep(
                    action_type="soil_moisture_manual_check",
                    description="सिंचाई का निर्णय लेने से पहले जड़ क्षेत्र में मिट्टी की नमी की जांच हाथ से छूकर करें।",
                    urgency="advisory",
                ),
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="दोपहर की धूप में पौधों की पत्तियों पर मुरझाने के लक्षणों की जांच करें।",
                    urgency="advisory",
                ),
            ],
        },
    },
    "heat_stress_consistent": {
        "en": {
            "headline": "Elevated ambient temperatures are consistent with thermal stress conditions.",
            "summary": "Ambient temperatures are higher than seasonal averages, which may impact crop vigor during sensitive growth stages.",
            "interpretation": "ERA5-Land reanalysis observations show sustained high temperatures that can accelerate evapotranspiration.",
            "steps": [
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="Inspect crop foliage and flowering condition in the morning for signs of heat impact.",
                    urgency="advisory",
                ),
                RecommendedNextStep(
                    action_type="ongoing_monitoring",
                    description="Monitor daily temperature forecasts and watch for continued heatwave alerts.",
                    urgency="routine",
                ),
            ],
        },
        "hi": {
            "headline": "बढ़ा हुआ तापमान फसल पर गर्मी के तनाव की स्थिति के अनुरूप है।",
            "summary": "परिवेश का तापमान मौसमी औसत से अधिक है, जो संवेदनशील विकास चरणों के दौरान फसल को प्रभावित कर सकता है।",
            "interpretation": "मौसम के आंकड़े लगातार उच्च तापमान दर्शाते हैं, जिससे वाष्पीकरण बढ़ सकता है।",
            "steps": [
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="सुबह के समय फसल की पत्तियों और फूलों की स्थिति का निरीक्षण करें।",
                    urgency="advisory",
                ),
                RecommendedNextStep(
                    action_type="ongoing_monitoring",
                    description="दैनिक तापमान पूर्वानुमान और लू (heatwave) की चेतावनियों पर नज़र रखें।",
                    urgency="routine",
                ),
            ],
        },
    },
    "combined_stress_consistent": {
        "en": {
            "headline": "Multiple indicators show consistent combined moisture and thermal stress.",
            "summary": "Below-normal precipitation, depleted soil moisture, and elevated temperatures coincide with depressed vegetative vigor.",
            "interpretation": "Compound environmental stress factors are present across both meteorological and satellite vegetation observations.",
            "steps": [
                RecommendedNextStep(
                    action_type="soil_moisture_manual_check",
                    description="Verify root zone soil moisture directly across multiple locations in your parcel.",
                    urgency="advisory",
                ),
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="Inspect crop foliage for visible wilting and heat curling.",
                    urgency="advisory",
                ),
            ],
        },
        "hi": {
            "headline": "आंकड़े नमी और तापमान दोनों के संयुक्त तनाव के अनुरूप संकेत देते हैं।",
            "summary": "कम वर्षा, मिट्टी की कम नमी और उच्च तापमान एक साथ फसल की हरियाली में गिरावट के साथ मेल खाते हैं।",
            "interpretation": "मौसम और उपग्रह दोनों आंकड़े मिलकर संयुक्त पर्यावरणीय तनाव (combined stress) की स्थिति दर्शाते हैं।",
            "steps": [
                RecommendedNextStep(
                    action_type="soil_moisture_manual_check",
                    description="खेत में कई स्थानों पर जड़ क्षेत्र की मिट्टी की नमी की प्रत्यक्ष जांच करें।",
                    urgency="advisory",
                ),
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="पत्तियों के मुरझाने और गर्मी से मुड़ने के लक्षणों की जांच करें।",
                    urgency="advisory",
                ),
            ],
        },
    },
    "favorable": {
        "en": {
            "headline": "Above-average vegetative vigor observed with supportive environmental conditions.",
            "summary": "Satellite observations show above-normal vegetation vigor supported by adequate precipitation and stable soil moisture.",
            "interpretation": "Environmental conditions and spectral vigor are aligned with robust crop development.",
            "steps": [
                RecommendedNextStep(
                    action_type="ongoing_monitoring",
                    description="Maintain routine field management and continue regular observation.",
                    urgency="routine",
                )
            ],
        },
        "hi": {
            "headline": "अनुकूल मौसम और पर्याप्त नमी के साथ फसल हरियाली सामान्य से बेहतर देखी गई है।",
            "summary": "उपग्रह आंकड़े पर्याप्त वर्षा और स्थिर मिट्टी की नमी के साथ फसल की बेहतर हरियाली दर्शाते हैं।",
            "interpretation": "मौसम की स्थिति और उपग्रह संकेत फसल के अच्छे विकास के अनुरूप हैं।",
            "steps": [
                RecommendedNextStep(
                    action_type="ongoing_monitoring",
                    description="खेत की नियमित देखभाल जारी रखें और सामान्य निगरानी बनाए रखें।",
                    urgency="routine",
                )
            ],
        },
    },
    "mixed": {
        "en": {
            "headline": "Divergent environmental signals observed across satellite and meteorological data.",
            "summary": "Vegetation greenness and meteorological indicators show contrasting trends; available remote sensors cannot determine the maintaining mechanism.",
            "interpretation": "Diverging signals exist between physical evidence streams; direct field verification is advised to confirm actual soil and crop status.",
            "steps": [
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="Check field moisture and crop foliage directly to resolve contrasting data indicators.",
                    urgency="advisory",
                )
            ],
        },
        "hi": {
            "headline": "उपग्रह और मौसम के संकेतों में परस्पर विपरीत या मिश्रित रुझान देखे गए हैं।",
            "summary": "फसल हरियाली और मौसम के आंकड़े अलग-अलग दिशा दर्शाते हैं; उपग्रह आंकड़े इसके अंतर्निहित कारण की पुष्टि नहीं कर सकते।",
            "interpretation": "आंकड़ों में भिन्नता देखी गई है; वास्तविक स्थिति जानने के लिए खेत का प्रत्यक्ष निरीक्षण करने की सलाह दी जाती है।",
            "steps": [
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="खेत में जाकर मिट्टी की नमी और फसल की वास्तविक स्थिति की जांच करें।",
                    urgency="advisory",
                )
            ],
        },
    },
    "insufficient_evidence": {
        "en": {
            "headline": "Environmental data is currently insufficient to perform a complete field assessment.",
            "summary": "One or more critical data sources were unavailable or impacted by observation lag or cloud cover; no definitive condition classification can be asserted.",
            "interpretation": "Due to missing satellite or weather data streams, an authoritative assessment cannot be formed remotely.",
            "steps": [
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="Rely on direct physical inspection of your crop and soil condition in the field.",
                    urgency="advisory",
                ),
                RecommendedNextStep(
                    action_type="missing_information_gathering",
                    description="Check back when newer satellite or weather passes become available.",
                    urgency="routine",
                ),
            ],
        },
        "hi": {
            "headline": "पूर्ण मूल्यांकन के लिए वर्तमान में उपग्रह या मौसम संबंधी आंकड़े अपर्याप्त हैं।",
            "summary": "बादल या डेटा अनुपलब्धता के कारण आवश्यक आंकड़े उपलब्ध नहीं हैं; कोई निश्चित निष्कर्ष नहीं निकाला जा सकता।",
            "interpretation": "पर्याप्त आंकड़े उपलब्ध न होने के कारण रिमोट सेंसिंग से स्थिति का पूर्ण मूल्यांकन संभव नहीं है।",
            "steps": [
                RecommendedNextStep(
                    action_type="field_visual_inspection",
                    description="खेत में जाकर स्वयं फसल और मिट्टी की स्थिति का प्रत्यक्ष निरीक्षण करें।",
                    urgency="advisory",
                ),
                RecommendedNextStep(
                    action_type="missing_information_gathering",
                    description="नवीनतम उपग्रह आंकड़े उपलब्ध होने पर पुनः जांच करें।",
                    urgency="routine",
                ),
            ],
        },
    },
}


def generate_deterministic_fallback_explanation(
    context: GeminiAssessmentContext,
) -> FarmerAgriculturalResponse:
    """Generates a 100% deterministic pure-Python explanation directly from context.

    Invoked when Gemini API fails, times out, or returns output failing validation.
    Zero external network calls, zero hallucinations, and sets is_fallback=True.
    """
    lang = context.presentation.target_language if context.presentation.target_language in ("en", "hi") else "en"
    cond_key = context.overall_condition if context.overall_condition in FALLBACK_TEMPLATES else "insufficient_evidence"
    tmpl = FALLBACK_TEMPLATES[cond_key][lang]

    # Extract clean observations from structured SupportingEvidenceItem
    observations: list[str] = []
    for pattern in context.identified_patterns:
        for ev in pattern.supporting_evidence:
            obs_str = f"{ev.source}: {ev.metric_name} = {ev.observed_value}"
            if ev.reference_context:
                obs_str += f" ({ev.reference_context})"
            observations.append(obs_str)

    if not observations:
        if context.missing_evidence_sources:
            missing_str = ", ".join(context.missing_evidence_sources)
            observations.append(f"Missing data streams: {missing_str}")
        else:
            observations.append("Baseline environmental monitoring recorded.")

    # Combine limitations
    limitations = list(context.limitations)
    if not limitations and context.maximum_data_lag_days:
        limitations.append(f"Data publication lag: up to {context.maximum_data_lag_days} days.")

    return FarmerAgriculturalResponse(
        language=lang,
        headline=tmpl["headline"],
        summary=tmpl["summary"],
        observations=observations,
        interpretation=tmpl["interpretation"],
        recommended_next_steps=list(tmpl["steps"]),
        limitations=limitations,
        is_fallback=True,
    )


# ==============================================================================
# Isolated Gemini Service API
# ==============================================================================

def explain_agricultural_assessment(
    context: GeminiAssessmentContext,
    client: GeminiModelClient | None = None,
    model: str | None = None,
) -> FarmerAgriculturalResponse:
    """Explains a deterministic agricultural assessment using Gemini 2.5 Flash with fallback (DEC-024).

    Flow:
    1. Builds prompt using build_gemini_prompt(context).
    2. Calls Gemini 2.5 Flash requesting structured JSON output conforming to FarmerAgriculturalResponse.
    3. Runs automated 3-stage validation on model output.
    4. If any failure or validation rejection occurs, returns deterministic fallback.

    Args:
        context: Authoritative GeminiAssessmentContext boundary envelope.
        client: Optional GeminiModelClient for dependency injection (defaults to DefaultGeminiClient).
        model: Optional model identifier (defaults to config.model / gemini-2.5-flash).

    Returns:
        FarmerAgriculturalResponse: Validated farmer-facing explanation payload.
    """
    if not isinstance(context, GeminiAssessmentContext):
        raise TypeError(
            f"context must be a GeminiAssessmentContext instance, got {type(context)!r}"
        )

    # Resolve client and model
    resolved_client = client if client is not None else DefaultGeminiClient()
    resolved_model = model if model is not None else config.model

    try:
        # Build authoritative prompt
        prompt_text = build_gemini_prompt(context)

        # Configure structured JSON output via Google GenAI SDK
        from google.genai import types

        generate_config = types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=FarmerAgriculturalResponse,
            temperature=0.2,
        )

        # Invoke model
        response_obj = resolved_client.generate_content(
            model=resolved_model,
            contents=prompt_text,
            config=generate_config,
        )

        # Parse text response
        raw_text = ""
        if hasattr(response_obj, "text") and response_obj.text:
            raw_text = response_obj.text
        elif isinstance(response_obj, str):
            raw_text = response_obj
        else:
            raw_text = str(response_obj)

        # Stage 1: Pydantic Schema Validation
        parsed_dict = json.loads(raw_text)
        validated_response = FarmerAgriculturalResponse.model_validate(parsed_dict)

        # Stage 2 & 3: Boundary & Epistemic Validation
        is_valid, reason = validate_response_payload(validated_response, context)
        if not is_valid:
            logger.warning("Gemini agricultural response failed boundary validation: %s", reason)
            return generate_deterministic_fallback_explanation(context)

        return validated_response

    except Exception as exc:
        logger.warning("Gemini explanation generation failed or raised error: %s", type(exc).__name__)
        return generate_deterministic_fallback_explanation(context)
